### ISSUE TITLE
Issues with players can't use macros

### ISSUE THREAD

**Issue by belkasro** [mclemente/fvtt-advanced-macros#46]
Players for some reason can't use macros in my pathfinder 2e game. Can't use any of them for some reason. Is it due to the break?

**Comment by mclemente** [comment]
Yes, it was related to the changes. It wasn't running macros from compendiums. Sorry for your troubles. Should be fixed on v1.19.1.

**Comment by mclemente** [comment]
Reopening this issue since the macros can't be run from sockets (e.g. Run as GM, etc).

**Comment by mhilbrunner** [comment]
Still occurs with me with latest D&D and v1.19.1. Items with Item Macros break in that they can't be rolled at all, without any console errors. v1.18 works fine. Thanks for the module by the way, it's pretty useful!

**Comment by mclemente** [comment]
@mhilbrunner I am not sure this is an issue with Advanced Macros.
Item Macros are running fine when rolling an item in the character sheet (with and without Advanced Macros enabled), but they aren't running when running the macro even with Advanced Macros disabled.
I've tested with a `item.rollAttack({ fastForward: true }); item.rollDamage({ fastForward: true });` macro, though. So a more complex macro might be broken in another way. Could you share one of your macros?

**Comment by mhilbrunner** [comment]
@mclemente Okay, I've re-updated and tested some more. It seems that my existing way of calling macros can't pass arguments anymore with the update:

```
game.macros.find(m => m.name === "draw-from-compendium").execute("Shared Roll Tables", "Wild Magic");
```

It simply does nothing, without any error. If I remove the arguments, it does call the macro successfully. With v1.18.1, the above works.

(I just got Item Macros calling macros that then actually roll the item as part of the macro, and Item Macros disable the default rolling. So if calling the other macro silently doesn't work, it isn't rolled. So the previous report was more of a symptom of the above.)

**Comment by MrVauxs** [comment]
Same problem in PF2e Animation Macros, the way everyone handles arguments is through an array, which causes the macros to never be ran at all.
Putting a maximum version for Advanced Macros in PF2e Animation Macrosuntil the ecosystem updates.

**Comment by mclemente** [comment]
Release 1.19.2 should address this issue. I've tested Item Macros such as the example from @mhilbrunner and other temporary macros.

**Comment by MrVauxs** [comment]
> Release 1.19.2 should address this issue. I've tested Item Macros such as the example from @mhilbrunner and other temporary macros.

The update only broke the existing macros in PF2e Animation Macros.
